name: photo_album
description: Photo album application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.1
  firebase_core: ^1.19.2
  firebase_auth: ^3.4.2
  cloud_firestore: ^3.3.0
  firebase_storage: ^10.3.2
  flutter_native_splash: ^2.2.5
  flutter_launcher_icons: ^0.9.3
  flutter_svg: ^1.1.1+1
  outline_search_bar: ^2.3.0
  moor_flutter: any
  titled_navigation_bar: ^5.0.0-nullsafety.0
  build_runner: ^2.2.0
  google_sign_in: ^5.4.0
  provider: ^6.0.3
  file_picker: ^4.6.1
  permission_handler: ^10.0.0
  zoom_widget: ^0.2.1
  matrix4_transform: ^2.0.1
  screenshot: ^1.2.3
  path_provider: ^2.0.11
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  nb_utils: ^4.6.16
  flutter_mobx: ^2.0.6+1
  device_info_plus: ^4.0.0
  image: ^3.2.0
  google_fonts: ^3.0.1
  url_launcher: ^6.1.5
  share: any
  package_info: any
  glass_kit: any
  flutter_image_compress: any
  image_cropper: ^2.0.3
  font_awesome_flutter: any
  flutter_vector_icons: any
  flutter_native_image: any
  pdf: ^3.8.1
  printing: ^5.9.1
  share_plus: ^4.0.10
  archive: ^3.3.0
  file_saver: ^0.1.0
  material_floating_search_bar: ^0.3.7
  keyboard_dismisser: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: any
  mobx_codegen: 2.0.7


flutter_native_splash:
  background_image: 'assets/images/splash.png'
  android: true
  ios: true

flutter_icons:
  image_path: 'assets/images/app_logo.png'
  android: true
  ios: true
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
    - family: TabBarIcons
      fonts:
        - asset: assets/fonts/BottomNavigation.ttf

