name: photo_album
description: Photo album application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.6
  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.9.2
  flutter_svg: ^1.0.3
  outline_search_bar: ^2.3.0
  moor_flutter: any
  titled_navigation_bar: ^5.0.0-nullsafety.0
  build_runner: ^2.1.7
  google_sign_in: ^5.2.4
  provider: ^6.0.2
  file_picker: ^4.5.0
  permission_handler: ^9.2.0
  zoom_widget: ^0.2.1
  matrix4_transform: ^2.0.1
  screenshot: ^1.2.3
  path_provider: ^2.0.9
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  nb_utils: ^4.4.10
  flutter_mobx: any
  device_info_plus: any
  image: any
  google_fonts: any
  url_launcher: any
  share: any
  package_info: any
  glass_kit: any
  flutter_image_compress: any
  image_cropper: any
  font_awesome_flutter: any
  flutter_vector_icons: any
  flutter_native_image: any
  pdf: ^3.7.3
  printing: ^5.7.5
  share_plus: ^4.0.4
  archive: ^3.3.0
  file_saver: ^0.1.0
  material_floating_search_bar: ^0.3.7
  keyboard_dismisser: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  moor_generator: any
  mobx_codegen: 2.0.6


flutter_native_splash:
  background_image: 'assets/images/splash.png'
  android: true
  ios: true

flutter_icons:
  image_path: 'assets/images/app_logo.png'
  android: true
  ios: true
  remove_alpha_ios: true


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
    - family: TabBarIcons
      fonts:
        - asset: assets/fonts/BottomNavigation.ttf

