name: photo_album
description: Photo album application

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.6
  cloud_firestore: ^3.1.7
  firebase_storage: ^10.2.6
  flutter_native_splash: ^2.0.1+1
  flutter_launcher_icons: ^0.9.2
  flutter_bloc: ^8.0.1
  flutter_svg: ^1.0.3
  outline_search_bar: ^2.3.0
 
 
  titled_navigation_bar: ^5.0.0-nullsafety.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_native_splash:
  background_image: 'assets/images/splash.png'
  android: true
  ios: true

#flutter_icons:
#  image_path: 'assets/images/appLauncher.png'
#  android: true
#  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/svgs/
    - assets/fonts/
    - assets/templatesImages/


  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
    - family: TabBarIcons
      fonts:
        - asset: assets/fonts/BottomNavigation.ttf

